function tableVar = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TABLEVAR = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a string array.
%
%  TABLEVAR = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  tableVar = importfile("D:\FreeNASSync\School Work\Graduate Work\First Year\ACS 505 [LAB]\Lab1\part_2_lab_1.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Sep-2020 17:56:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["waveform", "VarName2", "VarName3", "VarName4", "VarName5"];
opts.VariableTypes = ["string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["waveform", "VarName2", "VarName3", "VarName4", "VarName5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["waveform", "VarName2", "VarName3", "VarName4", "VarName5"], "EmptyFieldRule", "auto");

% Import the data
tableVar = readmatrix(filename, opts);

end