%% Intro 
clc
clear

addpath([pwd,'/Max_Oli_Data']);
%% Import Data

Dat = importfile('longitudinalaccelredleft.csv');

% Get all the constants
Dat_arr  = table2array(Dat);               % Array from table
BLK_Size = 136800;       % Blocksize constant
fs       = 45.6*10^3;       % Sampling rate constant
avg      = 3;     % Sampling rate constant
t        = ((0:1:BLK_Size-1)./fs);         % Time array for time plotting
CH_num   = 2;       % Number of Channels
Col1     = Dat_arr(:,1);

%% Parse through time data
clc

% We can locate certain data by the missing table values.
MIS       = ismissing(Dat_arr(:,2));         % Locate SSSSS
MIS_ind   = find(MIS == 1);      % Find missing in logical array
avg_start = MIS_ind(4:5:end);  % Index by 5 (just the way the data is set up
avg_end   = MIS_ind(5:5:end);
% Get the channel1 and channel2 time data. I am using cells for simple
% Data management. Arrays within cells are easy to index
for jj = 2:(2+1)
    CH = [];
    CH_big = [];
    for ii = 1:avg
        CH(ii,:) = Dat_arr(avg_start(ii)+1:avg_end(ii)-1,jj);
        CH_big   = [CH_big,CH(ii,:)];
    end
    CH_big_cell{jj-1} = CH_big;   % This is a large array 1xN for Gxx fnc
    CH_cell{jj-1}     = CH;       % This is a small array for Gxx fnc
end

%% Parse through freq data
[M,~] = size(Col1);
Freq_start = find(contains(Col1,'Frequency')); % Find the FRF Phase point

if length(Freq_start) == 1
    Freq_range = Freq_start+1:length(Col1);
    Freq_NI    = double(Col1(Freq_range));
else
    for ii = 1:CH_num-1
        Freq_range(ii,:) = Freq_start(ii)+1:Freq_start(ii+1)-1; % Channel 1 frequency range
    end
    Freq_range(ii+1,:)   = Freq_start(ii+1)+1:length(Col1);
    Freq_NI              = double(Col1(Freq_range));
end
%% Getting Freq Data From Sheet
for ii = 1:CH_num
    CHPSDX(ii,:)    = double(Dat_arr(Freq_range(ii,:),2));
    CHFRFMAG(ii,:)  = double(Dat_arr(Freq_range(ii,:),3));
    CHFRFPH(ii,:)   = double(Dat_arr(Freq_range(ii,:),4));
    CHCOH(ii,:)     = double(Dat_arr(Freq_range(ii,:),5));
end

%% Plotting Comparison
LW = 1.4;
LW2 = 1.0;

for ii = 2:CH_num
    % PSDX works

    figure(1);
    plot(Freq_NI,CHPSDX(ii,:),'Linewidth',LW); hold on;
    MyGen.title_plots(['NI PSDX, CH: ',num2str(ii)],'Frequency (Hz)','Mag (WU/Hz^2)',14);
    xlim([Freq_NI(1) Freq_NI(end)]); 
    grid on;
    ytickformat('%,.2f')
    
    figure(4);
    plot(Freq_NI,CHFRFMAG(ii,:),'Linewidth',LW); hold on;
    MyGen.title_plots(['NI FRF, Red Wax'],'Frequency (Hz)','Mag (WU/Hz^2)',14);
    xlim([Freq_NI(1) Freq_NI(end)]); 
    grid on;
    ytickformat('%,.2f')
end

[val,loc] = findpeaks(CHPSDX(2,:));
limit = max(val) - 50;
[val2,loc2] = find(val > limit);
f_pks = round(Freq_NI(1,loc(loc2)))


function Lab1Ch4Test = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  LAB1CH4TEST = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  LAB1CH4TEST = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Lab1Ch4Test = importfile1("C:\Users\mbluu\Desktop\MATLAB_Work\ACS505\Lab1_Ch4_Test.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Sep-2021 17:45:49

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Blocksize", "SamplingRate", "NumberOfAvg", "NumberOfChannels", "Coh"];
opts.VariableTypes = ["string", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
%opts = setvaropts(opts, "Blocksize", "InputFormat", "MM/dd/yyyy HH:mm:ss.SSS");

% Import the data
Lab1Ch4Test = readtable(filename, opts);

end


function [Gxx_avg,f_Gxx] = MyAvgGxx(xn,fs,Nrecs,win)
% [Gxx_avg,f_Gxx] = MyAvgGxx(xn,fs,Nrecs)
% Inputs:
% xn         = Input Vector Time Array
% fs         = Sampling Rate
% Nrecs      = Number of records desired
% Outputs:
% Gxx_Avg    = Average Gxx from the operation
% f_Gxx      = Frequency of the Gxx average
% Info:
% By: Matthew Luu
% Last Edit: 9/20/2020
% Finds average Gxx of signal given number of records

% Begin Code:
N = length(xn);
N_new = N/Nrecs;
df = fs/N_new;
xn_array = zeros(Nrecs,N_new);
window = win.';
L_window = length(window);
ms = sum(window.*window)/L_window;
window = window/sqrt(ms);

for a = 1:Nrecs
    xn_array(a,:) = xn(floor(1+(N_new*(a-1))):floor(N/Nrecs+(N_new*(a-1)))).*window;
    [Gxx(a,:),~,~,f_Gxx] =  MyPSDX(xn_array(a,:),fs);
end
Gxx_avg = sum(Gxx,1)./Nrecs;
RMS = sqrt(sum(Gxx_avg).*df);
disp(['The RMS of signal: ', num2str(RMS)]);

RMS = sqrt(max(Gxx_avg).*df);
disp(['The RMS of sine wave single: ', num2str(RMS)]);

end

function [Gxx_avg,f_Gxx] = MyAvgGxy(xn,yn,fs,Nrecs,win)
% [Gxx_avg,f_Gxx] = MyAvgGxx(xn,fs,Nrecs)
% Inputs:
% xn         = Input Vector Time Array
% yn         = Input Vector Time Array, 2 
% fs         = Sampling Rate
% Nrecs      = Number of records desired
% Outputs:
% Gxx_Avg    = Average Gxx from the operation between two signals
% f_Gxx      = Frequency of the Gxx average
% Info:
% By: Matthew Luu
% Last Edit: 9/20/2020
% Finds average Gxx of signal given number of records

% Begin Code:
N = length(xn);
N_new = N/Nrecs;
df = fs/N_new;
xn_array = zeros(Nrecs,N_new);
yn_array = zeros(Nrecs,N_new);

window = win.';
L_window = length(window);
ms = sum(window.*window)/L_window;
window = window/sqrt(ms);

for a = 1:Nrecs
    xn_array(a,:) = xn(floor(1+(N_new*(a-1))):floor(N/Nrecs+(N_new*(a-1)))).*window;
    yn_array(a,:) = yn(floor(1+(N_new*(a-1))):floor(N/Nrecs+(N_new*(a-1)))).*window;

    [Gxx(a,:),Sxx,f,f_Gxx] =  MyPSDXY(xn_array(a,:),yn_array(a,:),fs);
end

Gxx_avg = sum(Gxx,1)./Nrecs;
RMS = sqrt(sum(Gxx_avg).*df);
disp(['The RMS of signal: ', num2str(RMS)]);

RMS = sqrt(max(Gxx_avg).*df);
disp(['The RMS of sine wave single: ', num2str(RMS)]);

end
function [Gxx,Sxx,f_Sxx,f_Gxx] = MyPSDX(x,Fs)
% [Gxx,Sxx,f] = MyPSDX(x,Fs)
% Inputs:
% x  = signal
% Fs = Sampling Rate
% Outputs:
% Gxx   = Single Sided Power Spectral Density
% Sxx   = Double Sided Power Spectral Density (Parsevels)
% f_Sxx = Frequency Double Sided
% f_Gxx = Frequency Single Sided
% Info:
% By: Matthew Luu
% Last Edit: 10/22/2020

% Begin Code:
    dt = 1/Fs;
    Xm = fft(x)*dt;
    N  = length(Xm);
    df = Fs/N;
    if rem(N,2) == 0
        % even number of samples.
        f_Sxx = (0:1:N-1)*df;
        Sxx = (abs(Xm).^2) * df;
        length(Sxx);
        Gxx = [Sxx(1),2*Sxx(2:N/2),Sxx((N/2)+1)]; 
        Sxx = fftshift(Sxx);
        f_Gxx = f_Sxx(1:(N/2)+1);
        f_Sxx = Fs*(floor(N/-2):floor(-1+N/2))/N;
    else
        % odd number of samples.
        f_Sxx = (0:1:N-1)*df;
        Sxx = (abs(Xm).^2) * df;
        Gxx = [Sxx(1),2*Sxx(2:floor(N/2)),Sxx(floor(N/2)+1)]; 
        Sxx = fftshift(Sxx);
        f_Gxx = f_Sxx(1:floor(N/2)+1);
        f_Sxx = Fs*(floor((N-1)/-2):(floor(N-1)/2))/N;
    end    
end

function [Gxx,Sxx,f_Sxx,f_Gxx] = MyPSDXY(x,y,Fs)
% [Gxx,Sxx,f] = MyPSDX(x,Fs)
% Inputs:
% x  = signal
% Fs = Sampling Rate
% Outputs:
% Gxx   = Single Sided Power Spectral Density
% Sxx   = Double Sided Power Spectral Density (Parsevels)
% f_Sxx = Frequency Double Sided
% f_Gxx = Frequency Single Sided
% Info:
% By: Matthew Luu
% Last Edit: 10/22/2020

% Begin Code:
    dt = 1/Fs;
    Xm = fft(x)*dt;
    Ym = fft(y)*dt;
    N  = length(Xm);
    df = Fs/N;
    if rem(N,2) == 0
        % even number of samples.
        f_Sxx = (0:1:N-1)*df;
        Sxx = (conj(Xm).*Ym) * df;
        length(Sxx);
        Gxx = [Sxx(1),2*Sxx(2:N/2),Sxx((N/2)+1)]; 
        Sxx = fftshift(Sxx);
        f_Gxx = f_Sxx(1:(N/2)+1);
        f_Sxx = Fs*(floor(N/-2):floor(-1+N/2))/N;
    else
        % odd number of samples.
        f_Sxx = (0:1:N-1)*df;
        Sxx = (conj(Xm).*Ym) * df;
        Gxx = [Sxx(1),2*Sxx(2:floor(N/2)),Sxx(floor(N/2)+1)]; 
        Sxx = fftshift(Sxx);
        f_Gxx = f_Sxx(1:floor(N/2)+1);
        f_Sxx = Fs*(floor((N-1)/-2):(floor(N-1)/2))/N;
    end    
end
