%% Release Notes:
%      For use with: TESTING
%      Package: 1v0.
%  This script will take imported data form the CSV file generated by 
%  LabVIEW and parse out the necessary time series data as well as the FRF
%  (frequency) data.
%
%  HELP:
%  filename = the full name of the file you are trying to import, this is
%             is assuming it is a .csv file formatted in the standard way
%             that LABVIEW formats csv exports. If you are trying to import
%             a file that is not in the root folder that this function is
%             contained, you will need to include the entire filepath to
%             the file.
%  data_1_y = y data from the first channel
%  data_2_y = y data from the second channel
%  data_3_y = y data from the third channel
%  data_4_y = y data from the third channel
%      APSD = power spectral density of both channels
%   FRF_MAG = frf magnitude of both channels
% FRF_PHASE = frf phase of both channels
%       CoH = coherence of both channels
%     times = time vector for data_1_y and data_2_y
%     freqs = frequency vector for all other values

function [data_1_y,data_2_y,data_3_y,data_4_y,APSD,FRF_MAG,FRF_PHASE,CoH,times,freqs] = readLabVIEWCSV(filename)
tableVar = importfile(filename, [1, Inf]);
time_series_idx = find(strcmp([tableVar],'time'));     % find the row index that corresponds to the row above the start of the data stream
frequency_idx = find(strcmp([tableVar],'Frequency'));  % find the row index that corresponds to the row above the frequency data stream

dt_idx = find(strcmp([tableVar],'delta t')); % find the row index that corresponds to where delta t is located
dt = str2double(tableVar(dt_idx(1),2));      % delta t value is always one column from delta t index

state = 'find'; % set state machine
check = 1;      % set check
for count = 1:length(time_series_idx) % increment through whole time series
    if length(time_series_idx) == 1   % if you only have one average, you have to do something special to find all the values
        while strcmp(state,'find') == 1
            % loop through the vector to find the first empty cell, this
            % will correspond to the end of the time series vector
            test_loc = time_series_idx+check;
            test = strcmp(tableVar(test_loc,1),""); % if empty break
            if test == 1 % we found the empty cell, break
                state = 'done'; % set state machine
            else
                % note done looking...
                check = check + 1; % increment check
            end
        end
        tempy = tableVar(time_series_idx(1)+1:test_loc-1,2);
        data_1_y = [tempy];
        tempy = tableVar(time_series_idx(1)+1:test_loc-1,3);
        data_2_y = [tempy];
        tempy = tableVar(time_series_idx(1)+1:test_loc-1,4);
        data_3_y = [tempy];
        tempy = tableVar(time_series_idx(1)+1:test_loc-1,5);
        data_4_y = [tempy];
    else
        % we have multiple averages... 
        if count == 1
            % first time we get the data, we need to use the index vector
            % we calculated at the beginning to grab the whole series
            tempy = tableVar(time_series_idx(count)+1:time_series_idx(count+1)-6,2);
            data_1_y = [tempy];
            tempy = tableVar(time_series_idx(count)+1:time_series_idx(count+1)-6,3);
            data_2_y = [tempy];
            tempy = tableVar(time_series_idx(count)+1:time_series_idx(count+1)-6,4);
            data_3_y = [tempy];
            tempy = tableVar(time_series_idx(count)+1:time_series_idx(count+1)-6,5);
            data_4_y = [tempy];
        else
            % once we know how long all the time series vectors are, we can
            % use the length of the first series to find all the other data
            % points
            vec_length = length(tempy);
            tempy = tableVar(time_series_idx(count)+1:time_series_idx(count)+vec_length,2);
            data_1_y = [data_1_y;tempy];
            tempy = tableVar(time_series_idx(count)+1:time_series_idx(count)+vec_length,3);
            data_2_y = [data_2_y;tempy];
            tempy = tableVar(time_series_idx(count)+1:time_series_idx(count)+vec_length,4);
            data_3_y = [data_3_y;tempy];
            tempy = tableVar(time_series_idx(count)+1:time_series_idx(count)+vec_length,5);
            data_4_y = [data_4_y;tempy];
        end
    end
end

nums = length(frequency_idx);
for count = 1:nums
    % grab all of the frequency related data
    if nums == 1
        freqs(:,count) = tableVar(frequency_idx(count)+1:end,1);
        APSD(:,count) = tableVar(frequency_idx(count)+1:end,2);
        FRF_MAG(:,count) = tableVar(frequency_idx(count)+1:end,3);
        FRF_PHASE(:,count) = tableVar(frequency_idx(count)+1:end,4);
        CoH(:,count) = tableVar(frequency_idx(count)+1:end,5);
    elseif count == nums
        freqs(:,count) = tableVar(frequency_idx(count)+1:end,1);
        APSD(:,count) = tableVar(frequency_idx(count)+1:end,2);
        FRF_MAG(:,count) = tableVar(frequency_idx(count)+1:end,3);
        FRF_PHASE(:,count) = tableVar(frequency_idx(count)+1:end,4);
        CoH(:,count) = tableVar(frequency_idx(count)+1:end,5);
    else
        freqs(:,count) = tableVar(frequency_idx(count)+1:frequency_idx(count+1)-1,1);
        APSD(:,count) = tableVar(frequency_idx(count)+1:frequency_idx(count+1)-1,2);
        FRF_MAG(:,count) = tableVar(frequency_idx(count)+1:frequency_idx(count+1)-1,3);
        FRF_PHASE(:,count) = tableVar(frequency_idx(count)+1:frequency_idx(count+1)-1,4);
        CoH(:,count) = tableVar(frequency_idx(count)+1:frequency_idx(count+1)-1,5);
    end
end
% return all variables and convert to double type
N = length(data_1_y);
times = (0:N-1)*dt;
data_1_y = str2double(data_1_y);
data_2_y = str2double(data_2_y);
data_3_y = str2double(data_3_y);
data_4_y = str2double(data_4_y);
freqs = str2double(freqs);
APSD = str2double(APSD);
FRF_MAG = str2double(FRF_MAG);
FRF_PHASE = str2double(FRF_PHASE);
CoH = str2double(CoH);
end

